MMA-8336 exim
SpamExperts/exim pull request #18
Opened 2023-08-23 11:19 UTC by Vlad-Georgescu-n-able

2023-08-23 11:25 UTC, jbnable commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [d726d2fb\-7676\-4815\-be21\-bf679faab28a](https://ast.checkmarx.net/projects/96f4ad66-d6af-4532-af48-e260e32ae9ce/scans?id=d726d2fb-7676-4815-be21-bf679faab28a&branch=MMA-8336)

### Fixed Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Ext\-mbx\-locking: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-misc/Ext-mbx-locking#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/C006: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//configs/config.samples/C006#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/README: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//src/README#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/Ext\-maildir\+\+: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-misc/Ext-maildir++#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/README: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//src/src/auths/README#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Missing User Instruction|/x2man: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-docbook/x2man#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Asymmetric private key|/cert1: [2](https://github.com/SpamExperts/exim/blob/MMA-8336//test/aux-fixed/cert1#L2)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Asymmetric private key|/cert2: [2](https://github.com/SpamExperts/exim/blob/MMA-8336//test/aux-fixed/cert2#L2)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5820: [57](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5820#L57)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5720: [23](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5720#L23)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5600: [24](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5600#L24)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5720: [96](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5720#L96)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/C044: [31](https://github.com/SpamExperts/exim/blob/MMA-8336//configs/config.samples/C044#L31)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5710: [23](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5710#L23)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5610: [24](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5610#L24)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5710: [96](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5710#L96)|Query to find passwords and secrets in infrastructure code.
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|Passwords And Secrets \- Generic Private Key|/5650: [24](https://github.com/SpamExperts/exim/blob/MMA-8336//test/confs/5650#L24)|Query to find passwords and secrets in infrastructure code.
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|Image Version Not Explicit|/Ext\-maildir\+\+: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-misc/Ext-maildir++#L1)|Always tag the version of an image explicitly
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/C006: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//configs/config.samples/C006#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/Ext\-mbx\-locking: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-misc/Ext-mbx-locking#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/README: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//src/src/auths/README#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/x2man: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc-docbook/x2man#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/README: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//src/README#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
![LOW](https://user-images.githubusercontent.com/42570337/152952890-19e8bf82-63bd-45a0-9a01-4a324fc10635.png)|Healthcheck Instruction Missing|/Ext\-maildir\+\+: [1](https://github.com/SpamExperts/exim/blob/MMA-8336//doc/doc [...]

2023-09-01 06:46 UTC, bitsikas approved these changes

2023-09-01 06:50 UTC, bitsikas submitted a review, later dismissed

2023-09-01 08:49 UTC, georges96 approved these changes

2023-09-01 13:13 UTC, cosmingrz submitted a review, later dismissed

2023-09-04 12:05 UTC, georges96 approved these changes

2023-09-04 12:20 UTC, alin-f-tache approved these changes

2023-09-04 12:23 UTC, bitsikas requested changes
isn't this against the wrong branch ?

2023-09-04 12:58 UTC, Vlad-Georgescu-n-able commented
> isn't this against the wrong branch ?

[SE-README.md](https://github.com/SpamExperts/exim/blob/master/SE-README.md) is only on the master branch, the file doesn't exist on [exim-4.92+fixes+se+encr](https://github.com/SpamExperts/exim/tree/exim-4.92+fixes+se+encr).

2023-09-04 12:59 UTC, bitsikas approved these changes

2023-09-05 08:58 UTC, merged